ALTER TABLE candle_d ADD COLUMN security_type SMALLINT NOT NULL DEFAULT 1;
ALTER TABLE candle_1h ADD COLUMN security_type SMALLINT NOT NULL DEFAULT 1;
ALTER TABLE candle_1m ADD COLUMN security_type SMALLINT NOT NULL DEFAULT 1;
ALTER TABLE candle_1w ADD COLUMN security_type SMALLINT NOT NULL DEFAULT 1;
ALTER TABLE candle_4w ADD COLUMN security_type SMALLINT NOT NULL DEFAULT 1;
ALTER TABLE candle_3m ADD COLUMN security_type SMALLINT NOT NULL DEFAULT 1;
ALTER TABLE candle_5m ADD COLUMN security_type SMALLINT NOT NULL DEFAULT 1;
ALTER TABLE candle_15m ADD COLUMN security_type SMALLINT NOT NULL DEFAULT 1;